Temp feature
CSC207-2022F-UofT/course-project-budgetbites pull request #38
Opened 2022-11-18 20:26 UTC by aryangoel24

final mongodb implementation done with the help of aviral
added empty constructors to User and Order class
added get methods for each User attribute
changed all dateOrdered instances to string versions of LocalDateTime

2022-11-18 21:00 UTC, Aviral-03 commented on src/main/java/mainMongoDB.java
> +//        addToPastOrders("aryangoel24", order);
Delete the redundant code.

2022-11-18 21:02 UTC, Aviral-03 commented on src/main/java/mainMongoDB.java
> +    public static void updateAttributeByUsername (String username, String attribute, String attValue) {
Add another method for restaurant method which will extract attributes from the given input

2022-11-18 21:10 UTC, Aviral-03 requested changes
Overall good job, you have identified every aspect for the database, however there are several changes to be made. I have added two comments in the file, where some of the redundant code is written. Furthermore, Clean Architecture is little absent because the gateway and requestModel for the database is not created. However, you can add that later. But review the changes that I have commented in your file. Additionally, you could also create tests for MongoDB file.

2022-11-19 23:37 UTC, Aviral-03 requested changes

2022-11-19 23:37 UTC, Aviral-03 commented on src/main/java/mainMongoDB.java
> +
Add another method here to extract the menu item from the restaurant collection from MongoDB

2022-11-20 01:41 UTC, Aviral-03 submitted a review, later dismissed
Everything looks good to me. You can add tests for this class and work on the clean architecture connecting this class to gateways and use case interactor, then create another pull request so that that can be merged.

2022-11-20 01:44 UTC, nathan-cai commented on src/main/java/Entities/Order.java
> -    protected Restaurant restaurant;
Why does order no longer keep track of which restaurant it is for?

2022-11-20 01:51 UTC, nathan-cai requested changes
The database setup looks good. However, I noticed that you guys removed an instance variable fo restaurant in the order entity, I think we need this because it is important to show the user where the order came form in past orders. Creating gateways is the next step so that the rest of our classes can interact with the database. Good Job!

2022-11-20 02:01 UTC, aryangoel24 commented on src/main/java/Entities/Order.java
> -    protected Restaurant restaurant;
This is an important design decision, and based on group discussion, I have added it back and adjusted the relevant classes to account for this instance attribute.

2022-11-20 02:06 UTC, nathan-cai approved these changes

2022-11-20 02:13 UTC, darpanmishra approved these changes
Looks good to me.
Great job implementing our Database with Mongo.
Let’s see how we can connect our use cases to our presenters.

2022-11-20 02:13 UTC, merged